server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    connection-timeout: 5000ms
  port: 9004
  servlet:
    context-path: /product

spring:
  cloud:
    nacos:
      serverAddr: 43.143.154.173:8848
  application:
    name: product
  # dev|test|prod
  profiles:
    active: dev
  # jackson
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
